"""Generate the cleaned figure set used in the thesis Results section."""

from __future__ import annotations

import csv
import json
import shutil
from pathlib import Path

from .data_loaders import (
    load_byu_digitized,
    load_epj_phi_plus_table11,
    load_glasgow_spatial_matrices,
    load_josa_b_eccentricity,
    load_karan_theta_digitized,
    load_testing_reality_all_angles,
)
from .phase_matching import SPDCConfig
from .plots import plot_sinc2_phase_matching, plot_walkoff_effect
from .polarization_validation import (
    EPJ_SOURCE_URL,
    TESTING_REALITY_SOURCE_URL,
    fit_polarization_model,
    plot_polarization_validation,
    write_polarization_predictions,
)
from .spatial_validation import (
    GLASGOW_SOURCE_URL,
    JOSA_B_SOURCE_URL,
    plot_spatial_ring_validation,
)
from .theta_validation import (
    KARAN_SOURCE_URL,
    plot_byu_ring_diameter_validation,
    plot_theta_ring_validation,
)


def _remove_legacy_thesis_outputs(output: Path) -> None:
    """Remove files generated by the superseded, demo-oriented thesis run."""

    legacy_paths = [
        "accuracy_summary.md",
        "accuracy_summary.csv",
        "accuracy_summary.json",
        "simulation",
        "epj_polarization",
        "testing_reality_polarization",
        "glasgow_spatial",
        "custom_experimental",
        "ring_comparison",
        "proxy_power_scan",
    ]
    for name in legacy_paths:
        path = output / name
        if path.is_dir():
            shutil.rmtree(path)
        elif path.exists():
            path.unlink()
    stale_byu = output / "supplementary" / "byu_ring_diameter_validation.png"
    if stale_byu.exists():
        stale_byu.unlink()


def _summary_csv(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "figure",
        "role",
        "dataset",
        "source_url",
        "metric_type",
        "r_squared_agreement_percent",
        "rmse",
        "mae",
        "notes",
    ]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _fmt(value, digits: int = 4) -> str:
    if value is None:
        return ""
    return f"{value:.{digits}f}"


def _write_summary_markdown(path: Path, rows: list[dict], reports: dict) -> None:
    lines = [
        "# Validation Summary",
        "",
        "Theory-only figures explain the numerical model and carry no experimental agreement metric. "
        "R²-based agreement is reported only for fits to experimental coincidence measurements.",
        "",
        "| Figure | Dataset | Metric Type | Reported Metric | Source |",
        "| --- | --- | --- | --- | --- |",
    ]
    for row in rows:
        metric = row["notes"]
        lines.append(
            f"| `{row['figure']}` | {row['dataset']} | `{row['metric_type']}` | {metric} | {row['source_url']} |"
        )
    lines.extend(
        [
            "",
            "## Theta Validation Note",
            "",
            reports["theta"].get("warning", ""),
            (
                "Karan et al. report Type-I BBO experimental EMCCD images at "
                "`theta_p = 28.64 deg`, `28.74 deg`, and `28.95 deg`, alongside numerical images. "
                "The repository stores these literature theta markers; no ring-radius metric is "
                "calculated until traceable digitized radii are entered."
            ),
            "",
            "## Spatial Validation Note",
            "",
            reports["spatial"]["note"],
            (
                "The JOSA B literature value for Type-I BBO is retained in "
                "`supplementary/spatial_eccentricity_summary.csv`: experimental eccentricity "
                "`0.013` with statistical error `0.011` and systematic error `0.007`, "
                "consistent with a nearly circular BBO ring."
            ),
            "",
            "## Testing Reality Note",
            "",
            (
                "Testing Reality shows the expected high coincidences for parallel polarizers "
                "and low coincidences for perpendicular polarizers, but the dataset is "
                "experimentally imbalanced; therefore it is used as a non-ideal validation dataset."
            ),
        ]
    )
    path.write_text("\n".join(line for line in lines if line is not None) + "\n", encoding="utf-8")


def _write_figure_captions(path: Path, theta_report: dict, spatial_report: dict) -> None:
    captions = f"""# Figure Captions

## Figure 1: `model_sinc2_phase_matching.png`

Theory-only illustration of the finite-crystal phase-matching envelope
`sinc^2(Delta k L / 2)` and the modeled wavelength dependence for Type-I BBO.
This figure describes the numerical method; no experimental agreement metric is assigned.

## Figure 2: `theta_ring_validation.png`

Modeled non-collinear Type-I BBO ring radius as a function of optic-axis angle
for the 405 nm to 810 nm + 810 nm configuration. The vertical line gives the
calculated collinear phase-matching angle (`theta_PM = {theta_report['theta_pm_deg']:.3f} deg`).
The dotted reference line marks the approximately `29.0 deg` literature value
reported for this wavelength regime.
Markers identify theta values for experimental EMCCD images reported by Karan
et al. Radius values have not been digitized, so this figure currently provides
literature-linked visual context rather than a numerical ring-radius fit.

## Figure 3: `polarization_validation_epj_phi_plus.png`

Model vs experimental data for the EPJ Quantum Technology Table 11 Phi+ state.
Corrected coincidences use `Ncorr = Nc - Nacc`; error bars use the Poisson
approximation implemented here, `sqrt(Nc + Nacc)`. Balanced and fitted unbalanced
correlated Bell-state models are compared using R²-based agreement and RMSE.

## Figure 4: `polarization_validation_testing_reality.png`

Model vs experimental data for the public Testing Reality polarization dataset.
The dataset is treated as a non-ideal validation measurement because its
coincidence map is imbalanced. The plot reports R²-based agreement and RMSE
for the balanced and fitted unbalanced models.

## Figure 5: `spatial_ring_validation.png`

Qualitative spatial comparison between one readable Glasgow public spatial
matrix and the simulated Type-I BBO far-field ring. The Glasgow archive is not
a calibrated free-space ring scan, so radial profiles are shown as normalized
shape context only and no direct radius RMSE is reported. The selected matrix
is `{spatial_report.get('experimental_matrix', '')}`.

## Supplementary: `supplementary/walkoff_effect.png`

Theory-only illustration of pump spatial walk-off and Gaussian-overlap loss.
It is retained as supporting theory and is not used as experimental validation.
"""
    path.write_text(captions, encoding="utf-8")


def run_clean_thesis_outputs(
    config: SPDCConfig,
    output: str | Path,
    epj_data: str | Path,
    testing_reality_data: str | Path,
    karan_data: str | Path,
    byu_data: str | Path,
    glasgow_zip: str | Path,
    josa_data: str | Path,
    fit_offset: bool = False,
) -> dict:
    """Generate main Results figures and supplementary theory outputs."""

    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    supplementary = output / "supplementary"
    supplementary.mkdir(parents=True, exist_ok=True)
    _remove_legacy_thesis_outputs(output)

    plot_sinc2_phase_matching(
        config, output / "model_sinc2_phase_matching.png", theory_only=True
    )
    plot_walkoff_effect(
        config, supplementary / "walkoff_effect.png", theory_only=True
    )

    karan_rows = load_karan_theta_digitized(karan_data)
    theta_report = plot_theta_ring_validation(
        config, karan_rows, output / "theta_ring_validation.png"
    )

    byu_rows = load_byu_digitized(byu_data)
    byu_report = plot_byu_ring_diameter_validation(
        byu_rows,
        supplementary / "byu_ring_diameter_validation.png",
        fit_offset_enabled=fit_offset,
    )

    epj_rows = load_epj_phi_plus_table11(epj_data)
    epj_predictions, epj_report = fit_polarization_model(epj_rows, "EPJ Table 11 Phi+")
    plot_polarization_validation(
        epj_predictions,
        epj_report,
        output / "polarization_validation_epj_phi_plus.png",
        "EPJ Table 11 Phi+",
        EPJ_SOURCE_URL,
    )
    write_polarization_predictions(
        output / "polarization_validation_epj_phi_plus.csv", epj_predictions
    )

    testing_rows = load_testing_reality_all_angles(testing_reality_data)
    testing_predictions, testing_report = fit_polarization_model(
        testing_rows, "Testing Reality"
    )
    plot_polarization_validation(
        testing_predictions,
        testing_report,
        output / "polarization_validation_testing_reality.png",
        "Testing Reality",
        TESTING_REALITY_SOURCE_URL,
        note="Non-ideal open dataset: experimental imbalance is retained in the measurement.",
    )

    try:
        glasgow_matrices = load_glasgow_spatial_matrices(glasgow_zip)
    except FileNotFoundError:
        glasgow_matrices = []
    josa_rows = load_josa_b_eccentricity(josa_data)
    spatial_report = plot_spatial_ring_validation(
        config,
        glasgow_matrices,
        output / "spatial_ring_validation.png",
        supplementary / "spatial_eccentricity_summary.csv",
        josa_rows,
    )

    summary_rows = [
        {
            "figure": "model_sinc2_phase_matching.png",
            "role": "Methods/model explanation",
            "dataset": "None (model only)",
            "source_url": "",
            "metric_type": "theory_only",
            "r_squared_agreement_percent": "",
            "rmse": "",
            "mae": "",
            "notes": "No experimental agreement metric.",
        },
        {
            "figure": "theta_ring_validation.png",
            "role": "Theta/ring tuning validation",
            "dataset": "Karan et al. theta markers",
            "source_url": KARAN_SOURCE_URL,
            "metric_type": theta_report["metric_type"],
            "r_squared_agreement_percent": "",
            "rmse": _fmt(theta_report["rmse"]),
            "mae": _fmt(theta_report["mae"]),
            "notes": (
                "RMSE and MAE unavailable until ring radii are digitized."
                if theta_report["points"] == 0
                else f"RMSE={theta_report['rmse']:.4f}; MAE={theta_report['mae']:.4f}."
            ),
        },
        {
            "figure": "polarization_validation_epj_phi_plus.png",
            "role": "Primary Bell-state validation",
            "dataset": "EPJ Quantum Technology Table 11",
            "source_url": EPJ_SOURCE_URL,
            "metric_type": "model_vs_experimental_data",
            "r_squared_agreement_percent": _fmt(100.0 * epj_report["r_squared_unbalanced"], 2),
            "rmse": _fmt(epj_report["rmse_unbalanced"]),
            "mae": "",
            "notes": (
                f"R²-based agreement: balanced={100 * epj_report['r_squared_balanced']:.2f}%, "
                f"unbalanced={100 * epj_report['r_squared_unbalanced']:.2f}%; "
                f"RMSE={epj_report['rmse_unbalanced']:.4f}."
            ),
        },
        {
            "figure": "polarization_validation_testing_reality.png",
            "role": "Secondary non-ideal validation",
            "dataset": "Testing Reality data_allAngles.csv",
            "source_url": TESTING_REALITY_SOURCE_URL,
            "metric_type": "model_vs_experimental_data",
            "r_squared_agreement_percent": _fmt(
                100.0 * testing_report["r_squared_unbalanced"], 2
            ),
            "rmse": _fmt(testing_report["rmse_unbalanced"]),
            "mae": "",
            "notes": (
                f"R²-based agreement: balanced={100 * testing_report['r_squared_balanced']:.2f}%, "
                f"unbalanced={100 * testing_report['r_squared_unbalanced']:.2f}%; "
                f"RMSE={testing_report['rmse_unbalanced']:.4f}; non-ideal dataset."
            ),
        },
        {
            "figure": "spatial_ring_validation.png",
            "role": "Spatial/ring context",
            "dataset": "Glasgow spatial matrices; JOSA B eccentricity",
            "source_url": f"{GLASGOW_SOURCE_URL}; {JOSA_B_SOURCE_URL}",
            "metric_type": "qualitative_spatial_comparison",
            "r_squared_agreement_percent": "",
            "rmse": "",
            "mae": "",
            "notes": "No direct metric: optical radius calibration unavailable.",
        },
    ]
    reports = {
        "theta": theta_report,
        "byu_supplementary": byu_report,
        "epj_polarization": epj_report,
        "testing_reality_polarization": testing_report,
        "spatial": spatial_report,
    }
    _summary_csv(output / "validation_summary.csv", summary_rows)
    (output / "validation_summary.json").write_text(
        json.dumps({"figures": summary_rows, "reports": reports}, indent=2),
        encoding="utf-8",
    )
    _write_summary_markdown(output / "validation_summary.md", summary_rows, reports)
    _write_figure_captions(output / "figure_captions.md", theta_report, spatial_report)
    return reports
